### ISSUE TITLE
Available Balance is 0 (zero) after transaction

### ISSUE THREAD

**Issue by miracatici** [emesik/cardano-python#11] opened 2021-11-21 11:37 UTC
Hello, I'm using Docker containers for `cardano-wallet` and `cardano-node`. Container image versions are `inputoutput/cardano-wallet:2021.11.11` and `inputoutput/cardano-node:1.30.1` respectively. 

I would like to make the automatic transaction. However, When I made the first transaction with `cardano-python`, the available balance is shown as zero for a while. This timeout or cooldown time is varying from 5 seconds to forever. It also usually crash the script.

Is there anything that I'm missing to make proper transaction?  

```
wal = Wallet("WALLET_ID", backend=WalletREST(host='cardano-wallet', port=8090))
tx = wal.transfer(
       "destination_address",
        20,
        passphrase="xx",
        ttl=1
)
```

**Comment by emesik** [comment] 2021-11-21 13:46
The balance is zero at **the source wallet** for unspecified time **after the transfer** has been done? Do I understand it right?

**Comment by miracatici** [comment] 2021-11-21 14:07
> 

Exactly, one exception: not total balance, only 'available balance' is zero.

**Comment by emesik** [comment] 2021-11-21 17:41
Everything is OK and it has nothing to do with the Python module. Sending a payment manually you'd have ran into the same situation.

This is about UTxOs. You're probably using a test wallet where you deposited a single transaction before? It means there's only one UTxO and you spend it. Before the transaction gets accepted by the network and the change UTxO is confirmed to have landed in your wallet, you have to wait and see zero balance (because there aren't any other UTxOs available).

> is varying from 5 seconds to forever

This is the only thing that worries me here. How long was the longest "forever"?

**Comment by miracatici** [comment] 2021-11-21 18:06
Ah, I see. You understand that I'm a newbie :) When I revert the transfer direction (I mean wallet 2 to wallet 1 instead of 1 to 2) it made much more transactions than the other, because all the day I made the manual transfers from 1 to 2 so I have many UTxOs. Thanks for your fast reply.

**Closed** 2021-11-21 18:08 UTC

**Comment by emesik** [comment] 2021-11-21 18:11
Exactly. And this is something common to many cryptocurrencies based on UTxO model, like Bitcoin or Monero.
